name: mp3_music_converter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  audioplayers: ^0.17.4
  flutter_radio: ^0.1.8
  cached_network_image: ^2.5.0
  marquee: ^1.7.0
  hive_flutter: ^0.3.1
  hive: ^1.4.4+1
  file_picker: ^2.1.6
  share: ^0.6.5+4
  flutter_downloader: ^1.5.2
  permission_handler: ^5.1.0+2
  http: ^0.12.2
  path_provider: ^1.6.27
  pin_entry_text_field: ^0.1.4
  route_transitions: ^1.0.2
  image_picker: ^0.6.7+22
  toast: ^0.1.5
  flutter_spinkit: ^4.1.2+1
  jaynetwork: ^0.0.1
  provider: ^4.3.2+2
  flutter_svg:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+4
  downloads_path_provider: ^0.1.0
  dots_indicator: ^2.0.0
  geolocator: ^6.2.1
  geocoder: ^0.2.1
  flutter_switch: ^0.3.1
  rave_flutter: ^0.0.9-alpha+2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-Thin.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf